### ISSUE TITLE
Petite correction question 10

### ISSUE THREAD

**Issue by Vlequay** [PolytechLyon/4a-isi3-tp3-2016-2017-groupe-2-collin#1]
Votre TP est nickel, par contre vous n'avez pas utilisé la bonne méthode à la question 10.
Mockito vous permet de vérifier l'usage (ou le non-usage) des méthodes d'un manière très simple et rapide, allez jeter un oeil à la toute fin du cours :)
Ça ne vous prendra pas longtemps et c'est une technique qu'il est important de connaître.
Et comme ça après on en parle plus ;)

**Comment by LeaCollin** [comment]
En effet, solution efficace! Merci beaucoup.

**Comment by Vlequay** [comment]
De rien ! Bon ben nickel, je clos.
